# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.CharField(max_length=50)),
                ('val_date', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('ref_no', models.CharField(max_length=100)),
                ('debit', models.CharField(max_length=20)),
                ('credit', models.CharField(max_length=20)),
                ('balance', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=30)),
            ],
        ),
    ]
